In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math 
import hashlib

In [17]:
data = pd.read_csv('data/train.csv')
data.head(100)
len(data)

522412

In [12]:
data.card_id.value_counts()

f53417e1    162255
ecad2386     63340
7358e05e     25178
d292c32f     20410
e2fcccd2     18810
3692fd30     13678
03a08c3f      9405
54c5d545      9057
5064623a      8635
e71aba61      7813
73206397      6930
e2a1ca37      6906
03528b27      6630
06ef0828      6510
66f5e02e      4436
6a7bc718      4409
f888bf4c      4270
be7c618d      4248
39947756      4078
460f4063      3816
c0c5eb49      3557
4e02fbd3      3529
c680d3dd      3350
422da614      3333
1dc72b4d      2805
170f5944      2798
2bc6bb64      2717
fb7c70a3      2242
75759a0b      2217
1d64ced5      2187
             ...
9e52603f         1
2434b80a         1
fb608f63         1
72c30e4d         1
4e031e68         1
d6004e51         1
27ea9e9f         1
b8dd6afa         1
ba50c4fe         1
6723d5cf         1
5af8918c         1
14e07637         1
800fdb5c         1
aade46ef         1
0a1adda9         1
5e9e195d         1
768cce9a         1
d8704c2e         1
d71a818d         1
fa17c1ef         1
b2b678e1         1
0f6b2622         1
3aaff9a8         1
b4924f7c         1
1e2c67a7         1
289341ce         1
3e4c4a5c         1
fb631a94         1
66d1cc1d         1
470c3bc7         1
Name: card_id, Length: 1668, dtype: int64

In [14]:
data.corr()

,id,timestamp,C15,C16,C17,C18,C19,C20,C21,amount,isfraud
id,1.000000,0.997587,-0.018651,0.011418,0.255671,-0.333089,-0.156900,0.034557,0.347860,-0.025025,-0.024167
timestamp,0.997587,1.000000,-0.016096,0.012150,0.286264,-0.345968,-0.185009,0.041096,0.367994,-0.026694,-0.024398
C15,-0.018651,-0.016096,1.000000,0.148014,0.030097,-0.017020,0.006936,-0.005521,0.030765,0.024541,-0.004567
C16,0.011418,0.012150,0.148014,1.000000,0.066914,0.012226,0.014339,-0.016941,0.025182,0.018713,0.045341
C17,0.255671,0.286264,0.030097,0.066914,1.000000,-0.456372,-0.712730,0.156852,0.610945,0.073323,-0.010252
C18,-0.333089,-0.345968,-0.017020,0.012226,-0.456372,1.000000,0.401323,-0.097914,-0.616569,-0.048927,0.019256
C19,-0.156900,-0.185009,0.006936,0.014339,-0.712730,0.401323,1.000000,-0.184169,-0.478817,0.126511,0.004078
C20,0.034557,0.041096,-0.005521,-0.016941,0.156852,-0.097914,-0.184169,1.000000,-0.043508,-0.044812,0.004021
C21,0.347860,0.367994,0.030765,0.025182,0.610945,-0.616569,-0.478817,-0.043508,1.000000,0.057694,-0.048312
amount,-0.025025,-0.026694,0.024541,0.018713,0.073323,-0.048927,0.126511,-0.044812,0.057694,1.000000,-0.022021
isfraud,-0.024167,-0.024398,-0.004567,0.045341,-0.010252,0.019256,0.004078,0.004021,-0.048312,-0.022021,1.000000